### PR TITLE
Configurable approval count

### PR DESCRIPTION
**Pull request by niij**
This PR adds a new environment variable, `NUMBER_OF_APPROVALS_REQUIRED`, that allows you to specify the number of approvals that are required before it will apply the approval emoji. I kept the default as one. I tested this by setting `NUMBER_OF_APPROVALS_REQUIRED=2` and it worked as expected.

I also updated the docs with a minor change to note the `SLAPR_` prefix.

cc @AlexandreYang 

(note: I closed #35 in favor of this PR because I needed to update the _from_ branch base)

### CODE REVIEW

**Comment by niij** [comment]
@paulcacheux @safchain @juliogreff can I get a review on this PR? I don't see any codeowners/reviewers listed so I want to make sure it gets seen. Thanks!

**Comment by niij** [comment]
.

**Comment by niij** [comment]
bump

**Comment by paulcacheux** [comment]
@AlexandreYang can you take a look at this ?

**Comment by AlexandreYang** [comment]
Hi @niij, sorry for the late review/reply.

Thanks for the PR, it looks good to me and thanks for having tested it.

**Review by AlexandreYang — APPROVED** [review]

**Comment by niij** [comment]
No problem! Thank you for reviewing

**Pull request merged**
